language: node_js

env:
 - foo=bar
 
#build_image: shippable/minv2

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

matrix:
  exclude:
    - node_js: "0.12"
      foo=bar
  allow_failures:
    - node_js: "0.11"
      foo=bar
  
script: "npm run-script test-travis"

after_script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- --ui=bdd --reporter=xunit-file
  - ./node_modules/.bin/istanbul report cobertura --dir shippable/codecoverage/
  - cp README.md ./shippable
  
notifications:
     email:
         recipients:
             - vidya@shippable.com
             - buildsampletest@gmail.com
            # - vidyac.raghav@gmail.com
         on_success: always
         on_failure: always

archive: true

cache: true


